### ISSUE TITLE
デザイン2パターンの方針決定

### ISSUE THREAD

**Issue by uemasa** [uemasa/src_tree#1]
TOPページに書こうと思っている

# TODO
- [ ] パターンA
- [ ] パターンB

**Comment by uemasa** [comment]
### 下にある「Close and comment」をクリックするとIssueはクローズできます

**Comment by uemasa** [comment]
- [x] 「Reopen and comment」をクリックすると再オープンできます
- [x] @mentions, #refs, [links](), **formatting**, and <del>tags</del> supported
- [x] list syntax required (any unordered or ordered list supported)
- [x] this is a complete item
- [ ] this is an incomplete item

**Comment by uemasa** [comment]
クローズ

**Comment by uemasa** [comment]
どうでしょうか。スズメです。

![illustrain02-bird08](https://user-images.githubusercontent.com/11708014/77238680-e593c080-6c15-11ea-908a-d7c0284b981d.png)
